apiVersion: v1
kind: ConfigMap
metadata:
  name: unify-config
  namespace: unify

data:
  NODE_ENV: "production"

  GATEWAY_PORT: "8000"
  PORT: "4001"
  WORKSPACE_PORT: "8002"
  AI_AGENT_PORT: "8088"

  SERVICE_NAME: "unify-backend"

  API_PREFIX: "/api/v1"

  FRONTEND_URL: "http://frontend:3000"
  NEXT_PUBLIC_FRONTEND_URL: "http://frontend:3000"
  NEXT_PUBLIC_API_URL: "http://gateway:8000"

  AI_AGENT_URL: "http://ai-agent:8088"

  REDIS_URL: "redis://redis:6379/0"

  NEXT_PUBLIC_APP_NAME: "Unify"
  NEXT_PUBLIC_APP_ENV: "production"

  GEMINI_MODEL: "gemini-3.5-flash"

  REPO_OWNER: "narang24"
  REPO_NAME: "TravelStory-VN"

  PROMETHEUS_URL: ""
  KUBE_API_URL: ""